name: deploy-book

# Only run this when the master branch changes
on:
  workflow_dispatch:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    
    paths:
    - tutorial/**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: cache installation
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('tutorial/requirements.txt') }}

    - name: Install dependencies
      run: |
        pip install -r tutorial/requirements.txt
        
    # Publish the book to the docs folder
    - name: Build the book
      run: |
        jupyter-book build tutorial/
        
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        publish_dir: tutorial/_build/html
